/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/altar/scene.gltf -o src/pages/three-app/models/Altar.jsx -r public 
Author: SaltySpook (https://sketchfab.com/SaltySpook)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/altar-b8a21f20087849a89399a7db6596a25b
Title: altar
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export const Altar = (props) => {
  const { nodes, materials } = useGLTF('/models/altar/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload('/models/altar/scene.gltf');
