/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/dragon/scene.gltf -o src/pages/three-app/models/Dragon.jsx -r public 
Author: Al-Deezel (https://sketchfab.com/Al-dezel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-animation-flying-2fdae78e272c4994bb67336a289f11ef
Title: Dragon Animation Flying
*/
import { useGLTF, useAnimations } from '@react-three/drei';
import React, { useRef } from 'react';

export const Dragon = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/dragon/scene.gltf');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]} scale={7.319}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='RootNode0_0' scale={0.01}>
                <group name='skeletal3_3'>
                  <group name='GLTF_created_0'>
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name='dragon_wings22_2_correction'>
                      <group name='dragon_wings22_2' />
                    </group>
                    <skinnedMesh
                      name='Object_228'
                      geometry={nodes.Object_228.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_228.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/dragon/scene.gltf');
