/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/island2/scene.gltf -o src/pages/three-app/models/Island2.jsx -r public 
Author: Yaene (https://sketchfab.com/Yaene)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-island-c445a02a20084346be1d6e8fc6dca471
Title: Low Poly Island
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export const Island2 = (props) => {
  const { nodes, materials } = useGLTF('/models/island2/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.117, 2.276, 4.401]} scale={0.704}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.007']} />
          </group>
          <group position={[-2.988, 0.586, 6.544]} scale={0.678}>
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.005']} />
          </group>
          <group
            position={[6.571, 2.419, 1.072]}
            rotation={[0, 1.548, 0]}
            scale={[0.704, 0.856, 0.704]}
          >
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.007']} />
          </group>
          <group position={[-3.027, 1.486, -4.689]} scale={[0.678, 0.881, 0.678]}>
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.005']} />
          </group>
          <group position={[5.714, 2.565, 2.709]} scale={[0.625, 0.618, 0.625]}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_25.geometry} material={materials['Material.005']} />
          </group>
          <group
            position={[-2.232, 1.152, -2.92]}
            rotation={[-Math.PI, 0.143, -Math.PI]}
            scale={[0.87, 0.759, 0.87]}
          >
            <mesh geometry={nodes.Object_27.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_28.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_30.geometry} material={materials['Material.007']} />
          </group>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials['Material.003']}
            scale={10}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials['Material.001']}
            position={[0, 0.105, 0]}
            scale={13.111}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials['Material.009']}
            position={[0, 6.091, 0]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/island2/scene.gltf');
