/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/island3/scene.gltf -o src/pages/three-app/models/Island3.jsx -r public 
Author: Michal (https://sketchfab.com/Michal_K)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/island-e540ceb3ea5d49b185c898795e68ccb7
Title: Island
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export const Island3 = (props) => {
  const { nodes, materials } = useGLTF('/models/island3/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[-217.84, 69.884, 370.645]} rotation={[-1.52, -0.065, 0.019]} scale={18.518}>
        <mesh geometry={nodes.tree_Material013_0.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.tree_Material015_0.geometry} material={materials['Material.015']} />
      </group>
      <group position={[18.326, 200.902, -31.902]} rotation={[-Math.PI / 2, 0, 0.981]} scale={5.79}>
        <group position={[0.698, -0.479, -6.719]}>
          <group position={[0.001, -4.891, -7.029]}>
            <mesh
              geometry={nodes.Chest_Bottom_Wood_Metal_Iron_0.geometry}
              material={materials.Metal_Iron}
            />
            <mesh
              geometry={nodes.Chest_Bottom_Wood_Material005_0.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Chest_Bottom_Wood_Gem_Green_0.geometry}
              material={materials.Gem_Green}
            />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.earth_Cube013_rock_base_0.geometry}
        material={materials.rock_base}
        scale={36.358}
      />
      <mesh
        geometry={nodes.Icosphere000_Material014_0.geometry}
        material={materials['Material.014']}
        position={[-297.998, 187.313, -11.502]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={41.452}
      />
      <mesh
        geometry={nodes.kiogame3_Material_0.geometry}
        material={materials.Material}
        position={[25.663, 69.823, -31.365]}
        rotation={[0, -0.392, 0]}
        scale={113.592}
      />
      <mesh
        geometry={nodes.Circle_Material018_0.geometry}
        material={materials['Material.018']}
        position={[-424.496, 191.695, 215.471]}
        rotation={[-Math.PI / 2, 0, -1.349]}
        scale={[47.111, 47.111, 70.976]}
      />
      <mesh
        geometry={nodes.earth_Cube001_rock_base_0.geometry}
        material={materials.rock_base}
        scale={36.358}
      />
      <mesh
        geometry={nodes.earth_Cube002_Material003_0.geometry}
        material={materials['Material.003']}
        scale={36.358}
      />
      <mesh
        geometry={nodes.earth_Cube003_Material004_0.geometry}
        material={materials['Material.004']}
        scale={36.358}
      />
      <mesh
        geometry={nodes.earth_Cube004_rock_base_0.geometry}
        material={materials.rock_base}
        scale={36.358}
      />
    </group>
  );
};

useGLTF.preload('/models/island3/scene.gltf');
