/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable react/no-unknown-property */
/* eslint-disable prettier/prettier */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/island5/scene.gltf -o src/pages/three-app/models/Island5.jsx -r public 
Author: alfance (https://sketchfab.com/alfance)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-little-island-a1342470050b479caf5ed79dda88414d
Title: Low poly Little island
*/
import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export const Island5 = (props) => {
  const { nodes, materials } = useGLTF('/models/island5/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload('/models/island5/scene.gltf');
