/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/monster/scene.gltf -o src/pages/three-app/models/Monster.jsx -r public 
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-monster-1a28f8bd9b544b52b633591ee8b8d987
Title: alien monster
*/
import { useGLTF, useAnimations } from '@react-three/drei';
import React, { useRef, useState, useEffect } from 'react';

export const Monster = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/monster/scene.gltf');
  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState('ArmatureAction');

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='Armature_42' position={[-0.149, -0.091, 0.945]}>
                <group name='GLTF_created_0'>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name='Plane_41' />
                  <skinnedMesh
                    name='Object_7'
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.001']}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name='Object_8'
                    geometry={nodes.Object_8.geometry}
                    material={materials['Material.002']}
                    skeleton={nodes.Object_8.skeleton}
                  />
                </group>
              </group>
              <group name='Sphere_43'>
                <mesh
                  name='Object_51'
                  geometry={nodes.Object_51.geometry}
                  material={materials.material_0}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/monster/scene.gltf');
