/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/mossy_rock/scene.gltf -o src/pages/three-app/models/MossyRock.jsx -r public 
Author: Julyaaa (https://sketchfab.com/Julyaaa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mossy-rock-3406cbca74b2468a85188d15ba2d8e86
Title: Mossy Rock
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export const MossyRock = (props) => {
  const { nodes, materials } = useGLTF('/models/mossy_rock/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Rock_01_A}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/models/mossy_rock/scene.gltf');
