/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/sky/scene.gltf -o src/pages/three-app/models/Scene.jsx -r public 
Author: ritsuka (https://sketchfab.com/ritsuka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sd-sky-230315a-7b88df45719c4ce28e6df8c966c7c515
Title: SD_Sky_230315a
*/
import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

const SceneSky = (props) => {
  const { nodes, materials } = useGLTF('/models/sky/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        rotation={[1.55, 0.085, 1.813]}
        scale={150}
      />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Suzanne} />
    </group>
  );
};

useGLTF.preload('/models/sky/scene.gltf');

export default SceneSky;
