/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/stylized_rock/scene.gltf -o src/pages/three-app/models/StylizedRock.jsx -r public 
Author: skinny hands (https://sketchfab.com/skinnyhands)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-rock-47f2a1d475684327a4b9447772690cde
Title: Stylized  rock
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export const StylizedRock = (props) => {
  const { nodes, materials } = useGLTF('/models/stylized_rock/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.215}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.low_1}
            rotation={[Math.PI / 2, 0, -2.581]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/stylized_rock/scene.gltf');
