/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/sword/scene.gltf -o src/pages/three-app/models/Sword.jsx -r public 
Author: SJunior3d (https://sketchfab.com/sjunior3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-sword-403f64420e0b4ca69b7b5f2f8e0086b1
Title: Animated Sword
*/
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import React, { useRef, useState, useEffect } from 'react';

export const Sword = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/sword/scene.gltf');
  const { actions } = useAnimations(animations, group);

  const [animation, setAnimation] = useState('Take 001');

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation, actions]);

  useFrame((_, delta) => {
    group.current.rotation.y += 0.5 * delta;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0.008]}>
          <group name='cb87240bfbb943eea0a4580a88a5dd66fbx' rotation={[Math.PI / 2, 0, 0]}>
            <group name='Object_2'>
              <group name='RootNode'>
                <group name='Object_4'>
                  <primitive object={nodes._rootJoint} />
                  <group name='Object_6' rotation={[-Math.PI / 2, 0, 0]} />
                  <group name='Particle_View_001' rotation={[-Math.PI / 2, 0, 0]} />
                  <group name='sword_low' rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh
                    name='Object_7'
                    geometry={nodes.Object_7.geometry}
                    material={materials.Material_192}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/sword/scene.gltf');
